### ISSUE TITLE
表格的布局和样式能修改吗？我想在排序按钮附近加一个❌  这个可以实现吗？

### ISSUE THREAD

**Issue by BlinkZF** [ssy341/datatables-cn#428]
#### 4. 使用DataTables的配置信息

```
// 此处填写格式化代码

```

**Comment by BlinkZF** [comment]
点击×的时候时刻实现这一列数据的删除  这个好实现吗？如果要修改表格样式的话 在哪修改呢？

**Comment by occultskyrong** [comment]
### 增加按钮的方法

`columns.title`里面支持使用`html`

> https://datatables.net/reference/option/columns.title

官方说明

> Please note that when constructing a header, DataTables can only construct a simple header with a single cell for each column. Complex headers with colspan and rowspan attributes must either already be defined in the document, or be constructed using standard DOM / jQuery methods.

其中有`Comments `

> Please note that you can enter HTML markup in the title field and it will be interpreted.
I used this feature to include a `<div>` with a class value in order to enable custom CSS.

一个复杂表头的栗子

> https://www.datatables.net/examples/basic_init/complex_header.html

### 给个变通的方案

- 在页面的上边，把所有的`field`都列出来。
- 当然前端是一种多选的方式，默认全部选中。
- 如果用户不想查看某个列，取消勾选。对应全局中的某个数组`fieldsArray`
- 根据`fieldsArray`来构造`DT`中`columns`内容，在`columns`中删除或者`display:false`此列

这个方案的好处在于，不影响原生`DT`的样式，否则你需要根据`header-title`的长度来调整按钮的出现。同时`DT`在计算某列的宽度时也会出问题。

------
个人建议使用第二种方式，更灵活、简单
